### ISSUE TITLE
version conflict  for using default way of pipenv

### ISSUE THREAD

**Issue by thinksource** [awslabs/aws-serverlessrepo-python#23]
Hi, I find the last version of serverlessrepo 0.1.6 using pipenv package, but If I using pip install that it will conflict with other tools like localstack.

```
serverlessrepo 0.1.6 has requirement six~=1.11.0, but you'll have six 1.12.0 which is incompatible.  *********error here***********
Installing collected packages: six, airspeed, localstack
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: airspeed 0.5.5.dev20160812
    Uninstalling airspeed-0.5.5.dev20160812:
      Successfully uninstalled airspeed-0.5.5.dev20160812
Successfully installed airspeed-0.5.10 localstack-0.8.10 six-1.12.0
```

the last version localstack require six 1.12.0 while the serverlessrepo still lock the six version 1.11.0. Can you make your Pipfile.lock file using 

```
"six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
```

to 

```
"version": ">=1.11.0"
```
since it will block six or other dependence upgrade later on.

**Comment by paoptu023** [comment]
Hi, the Pipfile.lock is auto generated, and it's only applicable when you use pipenv to install serverlessrepo. Can you elaborate more on how you are using this library? If you do pip install, the dependency version is derived from [setup.py](https://github.com/awslabs/aws-serverlessrepo-python/blob/master/setup.py#L7-L12). We require six~=1.11.0, which is compatible with six 1.12.0.

**Comment by paoptu023** [comment]
Sorry for the late response. I have created a PR to change the version requirement for six, it should be able to fix your issue once merged.

**Comment by paoptu023** [comment]
Hi, the PR is merged, and the new version has been published to PyPI. Feel free to reopen the issue if you have additional questions.
